FROM ubuntu:16.04 
WORKDIR /
ENV FRONT_URL=*
RUN apt-get update && apt-get install -y curl
RUN apt-get install -y git
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt install -y nodejs
RUN node -v && npm -v
RUN git clone https://github.com/docker-hy/backend-example-docker
WORKDIR backend-example-docker/
RUN npm install

CMD ["npm","start"]