version: '3.5' 

services: 

    frontend: 
      image: exercise_1_10 
      build: . 
      ports: 
        - 5000:5000

    backend: 
      image: exercise_1_11 
      build: . 
      ports: 
        - 8000:8000